services:
  follow-claim:
    container_name: follow-claim
    image: missuo/follow-claim:latest
    restart: unless-stopped
    environment:
      - COOKIE=
      - BARK_URL=
      # Use UTC Time
      - SCHEDULED_TIME=00:05 